### ISSUE TITLE
brew formular removed

### ISSUE THREAD

**Issue by asxzy** [mejmo/mac-shrew#6]
Hi,

I was trying to install macshrew following the instruction.
When executing
```
brew install shrewsoft-vpn-client
```
error pops up:
```
Error: No available formula with the name "shrewsoft-vpn-client" 
==> Searching for a previously deleted formula...
shrewsoft-vpn-client was deleted from homebrew/core in commit 0b744ca667:
  shrewsoft-vpn-client: migrate to boneyard
  due to tuntap requirement

To show the formula before removal run:
  git -C "$(brew --repo homebrew/core)" show 0b744ca667^:Formula/shrewsoft-vpn-client.rb

If you still use this formula consider creating your own tap:
  https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap.html
```

**Comment by asxzy** [comment]
Tried to install manually:

1. install tuntap by ```brew cask install tuntap``` since the formula is removed ```due to tuntap requirement```

2. download old formula
```
wget https://raw.githubusercontent.com/Homebrew/homebrew-core/eeacd3e606fcb59351da347904bbb39fada32c7c/Formula/shrewsoft-vpn-client.rb
```

3. install the old formula
```
brew install shrewsoft-vpn-client.rb
```
got error:
```
Warning: Calling BottleSpecification.revision is deprecated!
Use BottleSpecification.rebuild instead.
/Users/asxzy/shrewsoft-vpn-client.rb:10:in `block in <class:ShrewsoftVpnClient>'

==> Installing dependencies for shrewsoft-vpn-client: cmake, qt
==> Installing shrewsoft-vpn-client dependency: cmake
==> Downloading https://homebrew.bintray.com/bottles/cmake-3.9.5.high_sierra.bot
######################################################################## 100.0%
==> Pouring cmake-3.9.5.high_sierra.bottle.tar.gz
==> Caveats
Emacs Lisp files have been installed to:
  /usr/local/share/emacs/site-lisp/cmake
==> Summary
🍺  /usr/local/Cellar/cmake/3.9.5: 2,267 files, 31.7MB
==> Installing shrewsoft-vpn-client dependency: qt
==> Downloading https://homebrew.bintray.com/bottles/qt-5.9.2.high_sierra.bottle
######################################################################## 100.0%
==> Pouring qt-5.9.2.high_sierra.bottle.tar.gz
==> Caveats
We agreed to the Qt opensource license for you.
If this is unacceptable you should uninstall.

This formula is keg-only, which means it was not symlinked into /usr/local,
because Qt 5 has CMake issues when linked.

If you need to have this software first in your PATH run:
  echo 'export PATH="/usr/local/opt/qt/bin:$PATH"' >> ~/.zshrc

For compilers to find this software you may need to set:
    LDFLAGS:  -L/usr/local/opt/qt/lib
    CPPFLAGS: -I/usr/local/opt/qt/include
For pkg-config to find this software you may need to set:
    PKG_CONFIG_PATH: /usr/local/opt/qt/lib/pkgconfig

==> Summary
🍺  /usr/local/Cellar/qt/5.9.2: 9,021 files, 279.6MB
==> Installing shrewsoft-vpn-client
Warning: Calling BottleSpecification.revision is deprecated!
Use BottleSpecification.rebuild instead.
/Users/asxzy/shrewsoft-vpn-client.rb:10:in `block in <class:ShrewsoftVpnClient>'

==> Downloading https://www.shrew.net/download/ike/ike-2.2.1-release.tbz2
######################################################################## 100.0%
==> cmake -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -D
Last 15 lines from /Users/asxzy/Library/Logs/Homebrew/shrewsoft-vpn-client/01.cmake:
-- Using library 
-- Using binary /usr/bin/flex ...
-- Using binary /usr/bin/bison ...
-- Enabled NAT Traversal support ...
-- Enabled LDAP Authentication support ...
CMake Error at /usr/local/Cellar/cmake/3.9.5/share/cmake/Modules/FindQt4.cmake:1318 (message):
  Found unsuitable Qt version "5.9.2" from /usr/local/opt/qt/bin/qmake, this
  code requires Qt 4.x
Call Stack (most recent call first):
  CMakeLists.txt:530 (find_package)


-- Configuring incomplete, errors occurred!
See also "/tmp/shrewsoft-vpn-client-20171107-10351-k33aii/ike/CMakeFiles/CMakeOutput.log".
See also "/tmp/shrewsoft-vpn-client-20171107-10351-k33aii/ike/CMakeFiles/CMakeError.log".

Do not report this issue to Homebrew/brew or Homebrew/core!
```

I will follow this and keep updated.

**Comment by opioom** [comment]
doesn't work. Sorry. 
1. brew install shrewsoft-vpn-client | message: Error: No formulae found in taps.
2. brew install shrewsoft-vpn-client.rb --without-gui | message: Error: invalid option: --without-gui
3. brew install shrewsoft-vpn-client.rb | message: Error: shrewsoft-vpn-client: undefined method `revision' for #<BottleSpecification:0x00007fcba41db510>

:(

**Comment by LKTPD** [comment]
Download it here 
https://www.amft-it.de/dist/macos/ShrewSoftVPNClient-2.1.1_macOS_Oct2017.pkg
found at [http://kb.amft-it.de/doku.php?id=kb-macos:shrewvpnclient-download&s[]=vpn](http://kb.amft-it.de/doku.php?id=kb-macos:shrewvpnclient-download&s[]=vpn)

you may retinize it on Mac.
http://retinizer.mikelpr.com/

**Comment by kim257** [comment]
> doesn't work. Sorry.
> 
> 1. brew install shrewsoft-vpn-client | message: Error: No formulae found in taps.
> 2. brew install shrewsoft-vpn-client.rb --without-gui | message: Error: invalid option: --without-gui
> 3. brew install shrewsoft-vpn-client.rb | message: Error: shrewsoft-vpn-client: undefined method `revision' for #BottleSpecification:0x00007fcba41db510
> 
> :(

the same :( 
mac 10.14.6
